version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prismo-app
    ports:
      - "3000:3000"
      - "9229:9229" # Porta para debug
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/prismo
      - MONGODB_URI=mongodb://mongo:27017/prismo
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - mongo
    networks:
      - prismo-network

  mongo:
    image: mongo:latest
    container_name: prismo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - prismo-network

  postgres:
    image: postgres:latest
    container_name: prismo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prismo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - prismo-network

volumes:
  mongo-data:
  postgres-data:

networks:
  prismo-network:
    driver: bridge
