# .gitea/workflows/deploy.yml
name: Atualizar e Iniciar Aplicação

on:
  push:
    branches:
      - main

jobs:
  update-and-start:
    runs-on: docker-arch
    container:
      image: node:20-slim  # Usando uma imagem oficial do Node.js
    
    steps:
      - name: Checkout código
        run: |
          echo "Fazendo checkout do código..."
          # Verificar se estamos no diretório correto
          pwd
          ls -la
          
          # Tentar atualizar o código em vez de clonar novamente
          if [ -d ".git" ]; then
            echo "Repositório git encontrado, atualizando..."
            git fetch origin
            git reset --hard origin/main
          else
            echo "Repositório git não encontrado, inicializando..."
            git init
            git remote add origin https://gitea.meesstudios.com.br/tevo/prismo-cloud.git
            git fetch origin
            git checkout -f main
          fi
          
          echo "✅ Checkout concluído com sucesso!"
          
      - name: Instalar dependências do projeto
        run: |
          echo "Instalando dependências do Node.js..."
          npm install
          echo "✅ Dependências instaladas com sucesso!"
          
      - name: Instalar PM2 globalmente
        run: |
          echo "Instalando PM2 globalmente..."
          npm install -g pm2
          echo "✅ PM2 instalado com sucesso!"

      - name: Gerar arquivos Prisma
        run: |
          echo "Gerando arquivos do Prisma..."
          npx prisma generate
          echo "✅ Arquivos Prisma gerados com sucesso!"

      - name: Gerar build da aplicação
        run: |
          echo "Gerando build da aplicação..."
          npm run build
          echo "✅ Build concluído com sucesso!"
          
      - name: Executar migração do Prisma
        run: |
          echo "Executando migração do Prisma..."
          npx prisma migrate deploy
          echo "✅ Migração concluída com sucesso!"

      - name: Criar arquivo de variáveis de ambiente
        run: |
          echo "Criando arquivo .env..."
          echo "PORT=3000" > .env
          echo "MONGODB_URI=mongodb://localhost:27017/prismo" >> .env
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/prismo" >> .env
          echo "✅ Arquivo .env criado com sucesso!"

      - name: Iniciar aplicação com PM2
        run: |
          echo "Instalando PM2 globalmente (caso ainda não esteja instalado)..."
          npm install -g pm2 || true
          echo "Iniciando aplicação com PM2..."
          pm2 delete prismo-cloud || true
          pm2 start dist/app.js --name prismo-cloud
          echo "✅ Aplicação iniciada em segundo plano!"

      - name: Verificar status da aplicação
        run: |
          echo "Aguardando inicialização da aplicação..."
          sleep 5
          pm2 status
          if pm2 show prismo-cloud | grep -q "online"; then
            echo "✅ Aplicação iniciada com sucesso!"
          else
            echo "⚠️ Verificar logs da aplicação para possíveis erros"
            pm2 logs prismo-cloud --lines 20 || true
            exit 1
          fi