# .gitea/workflows/deploy.yml
name: Atualizar e Iniciar Aplicação

on:
  push:
    branches:
      - main

jobs:
  update-and-start:
    runs-on: docker-arch
    container:
      image: node:20  # Usando a imagem do Node.js que inclui ferramentas comuns
    
    steps:
      - name: Verificar ferramentas disponíveis
        run: |
          echo "Verificando ferramentas disponíveis..."
          if ! command -v git &> /dev/null; then
            echo "Git não encontrado, instalando..."
            apt-get update -y && apt-get install -y git
          else
            echo "Git encontrado: $(git --version)"
          fi
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
      
      - name: Checkout código
        run: |
          echo "Fazendo checkout do código..."
          # Verificando a estrutura atual
          pwd
          ls -la
          
          # Clone com senha direta
          git clone https://tevo:Paodequeijo1!@gitea.meesstudios.com.br/tevo/prismo-cloud.git .
          echo "✅ Checkout concluído com sucesso!"
          
      - name: Configurar NPM para problemas de conectividade
        run: |
          echo "Configurando NPM para lidar com problemas de conectividade..."
          # Aumentar timeout do npm
          npm config set fetch-timeout 300000
          npm config set fetch-retries 5
          
          # Verificar se há um registry local ou alternativo disponível
          # Descomente a linha abaixo se você tiver um registry alternativo
          # npm config set registry http://seu-registry-local-ou-alternativo/
          
          # Verificar a configuração do npm
          echo "Configurações npm atuais:"
          npm config list
          
      - name: Instalar dependências do projeto
        run: |
          echo "Instalando dependências do Node.js..."
          # Tentar com --no-fund e --no-audit para reduzir tráfego de rede
          npm install --no-fund --no-audit --verbose || npm install --offline || echo "⚠️ Instalação com problemas, continuando com as dependências disponíveis"
          echo "✅ Processo de instalação de dependências finalizado"
          
      - name: Instalar PM2 globalmente
        run: |
          echo "Instalando PM2 globalmente..."
          npm install -g pm2 || echo "⚠️ Instalação do PM2 falhou, tentando continuar"
          echo "✅ Processo de instalação do PM2 finalizado"

      - name: Gerar arquivos Prisma
        run: |
          echo "Gerando arquivos do Prisma..."
          npx prisma generate
          echo "✅ Arquivos Prisma gerados com sucesso!"

      - name: Gerar build da aplicação
        run: |
          echo "Gerando build da aplicação..."
          npm run build
          echo "✅ Build concluído com sucesso!"
          
      - name: Executar migração do Prisma
        run: |
          echo "Executando migração do Prisma..."
          npx prisma migrate deploy
          echo "✅ Migração concluída com sucesso!"

      - name: Criar arquivo de variáveis de ambiente
        run: |
          echo "Criando arquivo .env..."
          echo "PORT=3000" > .env
          echo "MONGODB_URI=mongodb://localhost:27017/prismo" >> .env
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/prismo" >> .env
          echo "✅ Arquivo .env criado com sucesso!"

      - name: Iniciar aplicação com PM2
        run: |
          echo "Iniciando aplicação com PM2..."
          pm2 delete prismo-cloud || true
          pm2 start dist/app.js --name prismo-cloud
          echo "✅ Aplicação iniciada em segundo plano!"

      - name: Verificar status da aplicação
        run: |
          echo "Aguardando inicialização da aplicação..."
          sleep 5
          pm2 status
          if pm2 show prismo-cloud | grep -q "online"; then
            echo "✅ Aplicação iniciada com sucesso!"
          else
            echo "⚠️ Verificar logs da aplicação para possíveis erros"
            pm2 logs prismo-cloud --lines 20 || true
            exit 1
          fi