# .gitea/workflows/deploy.yml
name: Atualizar e Iniciar Aplicação

on:
  push:
    branches:
      - main

jobs:
  update-and-start:
    runs-on: docker-arch

    steps:
      - name: Navegar para diretório do projeto
        run: |
          cd /home/estevao/git/prismo-cloud
          echo "Iniciando processo de atualização em $(pwd)..."

      - name: Atualizar código (git pull)
        run: |
          cd /home/estevao/git/prismo-cloud
          echo "Atualizando código do repositório..."
          git pull origin main
          echo "✅ Código atualizado com sucesso!"

      - name: Instalar dependências
        run: |
          cd /home/estevao/git/prismo-cloud
          echo "Instalando dependências do Node.js..."
          npm install
          echo "✅ Dependências instaladas com sucesso!"

      - name: Iniciar containers com Docker Compose
        run: |
          cd /home/estevao/git/prismo-cloud
          echo "Iniciando containers com Docker Compose..."
          docker compose up -d
          echo "✅ Containers iniciados em segundo plano!"

      - name: Iniciar aplicação
        run: |
          cd /home/estevao/git/prismo-cloud
          echo "Iniciando aplicação com npm..."
          npm run start &
          echo "✅ Aplicação iniciada em segundo plano!"

      - name: Verificar status da aplicação
        run: |
          echo "Aguardando inicialização da aplicação..."
          sleep 10
          ps aux | grep "npm run start" | grep -v grep
          if [ $? -eq 0 ]; then
            echo "✅ Aplicação iniciada com sucesso!"
          else
            echo "⚠️ Verificar logs da aplicação para possíveis erros"
          fi